# This compose file will deploy the services, and bootup a mongo server.

# Copyright IBM Corp., All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Local `/opt/cello/mongo` will be used for the db storage.

#  cello-nginx: proxy to access operator dashboard service, listen on 8080
#  cello-operator-dashboard: dashboard service for operators
#  cello-user-dashboard: user service of cello, listen on 8081
#  engine: engine service of cello to provide RESTful APIs, listen on 80
#  cello-mongo: mongo db
#  cello-crypot-server: service of genarating the fabric config files
#
version: '3.2'
services:
  # mongo database, may use others in future
  mongo:
    image: mongo:3.4.10
    hostname: cello-mongo
    container_name: cello-mongo
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
        reservations:
          cpus: '0.10'
          memory: 256M
    ports:
      #- "27017:27017"  # use follow line instead in production env
      - "0.0.0.0:27017:27017"
      - "0.0.0.0:27018:27018"
    environment:
      - NO_USED=0
    volumes:
      - /opt/cello/mongo:/data/db

  # TODO: we may use one mongo instance, that should be enough
  dashboard_mongo:
    image: mongo:3.4.10
    hostname: cello-dashboard_mongo
    container_name: cello-dashboard_mongo
    restart: unless-stopped
    environment:
      - NO_USED=0
    volumes:
      - /opt/cello/dashboard_mongo:/data/db

  nfs:
    image: itsthenetwork/nfs-server-alpine:9
    restart: unless-stopped
    environment:
      - SHARED_DIRECTORY=/cello
    volumes:
      - /var/crypto_url/cello:/cello
    privileged: true
    network_mode: host

  crypto_url:
    image:  handchain/cello-crypto-server
    hostname: crypto_server
    container_name: crypto_server
    restart: unless-stopped
    volumes:
      - /var/crypto_url:/var/crypto_url
    ports:
      - 9906:9906
